image: bscpm/citools

cache:
  untracked: true
  key: "$CI_PIPELINE_ID"

build:
  stage: build
  script:
    - ./bootstrap
    - ./configure --disable-instrumentation --disable-instrumentation-debug --enable-coverage
    - make

coverage:
  stage: test
  before_script:
    # Re-build in case stage is executed by another runner
    - >
      if [ ! -f Makefile ] ; then
        ./bootstrap ;
        ./configure --disable-instrumentation --disable-instrumentation-debug --enable-coverage
        make
      fi
  script:
    - make check
    - gcovr -r .
  coverage: '/TOTAL.*\s+(\d+\%)/'
