version: 2

formats: [pdf,htmlzip]

sphinx:
  configuration: doc/user_guide/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - autotools-dev
    - autoconf
    - libtool
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_build:
    - ./bootstrap
    - ./configure
    - make sphinx-manpages
python:
   install:
   - requirements: doc/user_guide/requirements.txt