#################### FILES ##########################
SUB_DIRS= LB_MPI \
    dlb \
    LB_arch \
    LB_policies \
    DPD \
    LB_comm \
    LB_numThreads

############### CHOOSE THE COMMUNICATION MODEL #########
############### SHARED MEMORY OR SOCKETS ############### 

OBJ_MPI= LB_comm/comm_lend_light.o \
	LB_comm/comm_shMem.o \
	LB_MPI/MPI_interface.o \
	LB_MPI/process_MPI.o \
	LB_comm/comm_map.o \
	#LB_MPI/MPI_interfaceF.o \

OBJ32_MPI=LB_comm/comm_lend_light32.o \
	LB_comm/comm_shMem32.o \
	LB_MPI/MPI_interface32.o \
	LB_MPI/process_MPI32.o \
	LB_MPI/MPI_interfaceF32.o \
	LB_comm/comm_map32.o \

OBJ_MPI2= LB_comm/comm_lend_light-mpi2.o \
	LB_comm/comm_shMem-mpi2.o \
	LB_MPI/MPI_interface-mpi2.o \
	LB_MPI/process_MPI-mpi2.o \
	LB_MPI/MPI_interfaceF-mpi2.o \
	LB_comm/comm_map-mpi2.o \

OBJ32_MPI2=LB_comm/comm_lend_light32-mpi2.o \
	LB_comm/comm_shMem32-mpi2.o \
	LB_MPI/MPI_interface32-mpi2.o \
	LB_MPI/process_MPI32-mpi2.o \
	LB_MPI/MPI_interfaceF32-mpi2.o \
	LB_comm/comm_map32-mpi2.o \


OBJ=dlb/dlb_API.o \
    DPD/DPD.o \
    LB_arch/MyTime.o \
    LB_policies/JustProf.o \
    LB_policies/Lend.o \
    LB_policies/Weight.o \
    LB_policies/Lend_simple.o \
    LB_policies/LeWI_active.o \
    LB_policies/Lewi_map.o \
    LB_numThreads/numThreads.o \
    LB_policies/DWB_Eco.o \
    LB_arch/common.o \
    LB_policies/Lend_light.o \
    LB_MPI/tracing.o \

OBJ32=dlb/dlb_API32.o \
    DPD/DPD32.o \
    LB_arch/MyTime32.o \
    LB_policies/JustProf32.o \
    LB_policies/Lend32.o \
    LB_policies/Weight32.o \
    LB_policies/Lend_simple32.o \
    LB_policies/LeWI_active32.o \
    LB_numThreads/numThreads32.o \
    LB_policies/DWB_Eco32.o \
    LB_arch/common32.o \
    LB_policies/Lend_light32.o \
    LB_MPI/tracing32.o \

INTERCEPT_OBJ= LB_MPI/MPI_intercept.o 

INTERCEPT_OBJ32= LB_MPI/MPI_intercept32.o 

INTERCEPT_OBJ_MPI2= LB_MPI/MPI_intercept-mpi2.o 

INTERCEPT_OBJ32_MPI2= LB_MPI/MPI_intercept32-mpi2.o 

DEPENDS= Makefile LB_MPI/MPI_calls_coded.h dlb/dlb_API.h LB_numThreads/numThreads.h LB_comm/comm.h

