#################### FILES ##########################
SUB_DIRS= LB_MPI \
    dlb \
    LB_arch \
    LB_policies \
    DPD \
    LB_comm \
    LB_numThreads

SOCKT_OBJ= LB_comm/comm_sockets.o

SHMEM_OBJ=LB_comm/comm_shMem.o

SOCKT_OBJ32= LB_comm/comm_sockets32.o

SHMEM_OBJ32=LB_comm/comm_shMem32.o

############### CHOOSE THE COMMUNICATION MODEL #########
############### SHARED MEMORY OR SOCKETS ############### 

COMM_OBJ=$(SHMEM_OBJ)

COMM_OBJ32=$(SHMEM_OBJ32)

OBJ= LB_MPI/MPI_interface.o \
    LB_MPI/process_MPI.o \
    dlb/dlb_API.o DPD/DPD.o \
    LB_arch/MyTime.o \
    LB_policies/JustProf.o \
    LB_policies/Lend.o \
    LB_policies/Weight.o \
    LB_policies/Lend_simple.o \
    LB_policies/LeWI_active.o \
    LB_numThreads/numThreads.o \
    LB_policies/DWB_Eco.o \
    LB_arch/common.o \
    LB_policies/Lend_light.o \
    LB_comm/comm_lend_light.o \
    $(COMM_OBJ)

OBJ32= LB_MPI/MPI_interface32.o \
    LB_MPI/process_MPI32.o \
    dlb/dlb_API32.o  \
    DPD/DPD32.o \
    LB_arch/MyTime32.o \
    LB_policies/JustProf32.o \
    LB_policies/Lend32.o \
    LB_policies/Weight32.o \
    LB_policies/Lend_simple32.o \
    LB_policies/LeWI_active32.o \
    LB_numThreads/numThreads32.o \
    LB_policies/DWB_Eco32.o \
    LB_arch/common32.o \
    LB_policies/Lend_light32.o \
    LB_comm/comm_lend_light32.o  \
    $(COMM_OBJ32)

INTERCEPT_OBJ= LB_MPI/MPI_intercept.o

INTERCEPT_OBJ32= LB_MPI/MPI_intercept32.o

DEPENDS= Makefile LB_MPI/MPI_calls_coded.h dlb/dlb_API.h LB_numThreads/numThreads.h LB_comm/comm.h

