#!/bin/bash

pcf_file=$1                                     

cat >> $pcf_file <<EOF

EVENT_TYPE
0    800000	DLB Threads used

EVENT_TYPE
0    800020	DLB runtime 
VALUES
0      User code
1      Init
2      Into MPI Call
3      Out MPI Call
4      UpdateResources

EVENT_TYPE
0    800021	DLB Iteration

EVENT_TYPE
0    800030	DLB Idle Threads

EOF


