#!/bin/bash

pcf_file=$1                                     

cat >> $pcf_file <<EOF

EVENT_TYPE
0    800000	DLB Threads used

EVENT_TYPE
0    800020	DLB runtime 
VALUES
0      User code
1      Init
2      Into MPI Call
3      Out MPI Call
4      UpdateResources
5      ReturnClaimed

EVENT_TYPE
0    800040	DLB Iteration

EVENT_TYPE
0    800030	DLB Idle Threads

EVENT_TYPE
0    800050	DLB mode 
VALUES
0      not ready
1      Enabled
2      Disabled
3      Single

EOF


